version: '3.8'

services:
  frontend:
    build:
      context: ./tinytales-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://tinytales-backend:8000  # Update if needed
    depends_on:
      - backend

  backend:
    build:
      context: ./tinytales-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENV=production  # Add more as needed
