services:
  - type: web
    name: tinytales-frontend
    env: docker
    plan: free
    dockerContext: ./tinytales-frontend
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://tinytales-backend.onrender.com

  - type: web
    name: tinytales-backend
    env: docker
    plan: free
    dockerContext: ./tinytales-backend
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
