services:
  - type: web
    name: tinytales-frontend
    env: docker
    plan: free
    build:
      context: ./tinytales-frontend
      dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://tinytales-backend.onrender.com

  - type: web
    name: tinytales-backend
    env: docker
    plan: free
    build:
      context: ./tinytales-backend
      dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: ENV
        value: production
      # Add more env vars or use dashboard secrets if needed
